runtime: php55 # Replace with php73 to use the PHP 7.3 runtime

handlers:

- url: /(.+\.php)$
  script: \1

# Serve a directory as a static resource.
- url: /
  script: index.php

- url: /css
  static_dir: css

- url: /bodybg
  static_dir: bodybg

- url: /js
  static_dir: js

- url: /color
  static_dir: color

- url: /font-awesome
  static_dir: font-awesome

- url: /fonts
  static_dir: fonts

- url: /assets
  static_dir: assets

- url: /plugins
  static_dir: plugins

- url: /contactform
  static_dir: contactform

- url: /resources
  static_dir: resources

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$

